import { Router } from 'express';
import { z } from 'zod';
import { randomUUID } from 'crypto';
import { query } from '../db/pool.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
const router=Router(); router.use(requireAuth,requireRole('admin','staff','operator'));
const printer=z.object({name:z.string().min(2).max(120),model:z.string().max(120).optional(),ip_address:z.string().max(64).optional(),location:z.string().max(200).optional(),status:z.enum(['online','offline','maintenance']).default('offline')});
router.get('/',async(req,res,next)=>{try{const r=await query('SELECT * FROM printers ORDER BY created_at DESC');res.json({success:true,data:r.rows});}catch(e){next(e);}});
router.post('/',async(req,res,next)=>{try{const b=printer.parse(req.body);const r=await query(`INSERT INTO printers(id,name,model,ip_address,location,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[randomUUID(),b.name,b.model||null,b.ip_address||null,b.location||null,b.status]);res.status(201).json({success:true,data:r.rows[0]});}catch(e){next(e);}});
router.patch('/:id',async(req,res,next)=>{try{const b=printer.partial().parse(req.body);const fields=[];const vals=[];for(const[k,v]of Object.entries(b)){fields.push(`${k}=$${vals.length+1}`);vals.push(v);}if(!fields.length)return res.status(400).json({success:false,message:'No changes supplied.'});vals.push(req.params.id);const r=await query(`UPDATE printers SET ${fields.join(',')},updated_at=NOW() WHERE id=$${vals.length} RETURNING *`,vals);res.json({success:true,data:r.rows[0]});}catch(e){next(e);}});
router.delete('/:id',async(req,res,next)=>{try{await query('DELETE FROM printers WHERE id=$1',[req.params.id]);res.status(204).end();}catch(e){next(e);}});
export default router;
