import { Router } from 'express';
import crypto from 'node:crypto';
import { z } from 'zod';
import { query } from '../db/pool.js';
import { requireAuth, requireRoles } from '../middleware/auth.js';

const router=Router();
const jobSchema=z.object({stationToken:z.string().uuid(),fileName:z.string().min(1).max(255),storagePath:z.string().min(1).max(1000),mimeType:z.string().max(120),fileSize:z.number().int().positive().max(50_000_000),copies:z.number().int().min(1).max(100).default(1),pages:z.number().int().min(1).max(1000).default(1),colorMode:z.enum(['color','bw']).default('bw'),paperSize:z.string().max(30).default('A4'),orientation:z.enum(['portrait','landscape']).default('portrait')});
router.post('/public',async(req,res,next)=>{try{const p=jobSchema.parse(req.body);const {rows}=await query(`SELECT p.id,p.status,p.is_enabled FROM qr_codes q JOIN printers p ON p.id=q.printer_id WHERE q.token=$1 AND q.is_active=true AND (q.expires_at IS NULL OR q.expires_at>now())`,[p.stationToken]);const printer=rows[0];if(!printer||!printer.is_enabled||printer.status!=='online')return res.status(409).json({success:false,message:'Printer is currently unavailable.'});const jobId=crypto.randomUUID();const client=await import('../db/pool.js').then(m=>m.pool.connect());try{await client.query('BEGIN');await client.query(`INSERT INTO print_jobs(id,printer_id,copies,pages,color_mode,paper_size,orientation,status) VALUES($1,$2,$3,$4,$5,$6,$7,'queued')`,[jobId,printer.id,p.copies,p.pages,p.colorMode,p.paperSize,p.orientation]);await client.query(`INSERT INTO print_job_files(print_job_id,file_name,storage_path,mime_type,file_size) VALUES($1,$2,$3,$4,$5)`,[jobId,p.fileName,p.storagePath,p.mimeType,p.fileSize]);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}res.status(201).json({success:true,data:{jobId,status:'queued'}});}catch(e){next(e);}});
router.use(requireAuth,requireRoles('admin','staff','operator'));
router.get('/',async(req,res,next)=>{try{const {rows}=await query(`SELECT j.*,p.name printer_name,f.file_name FROM print_jobs j JOIN printers p ON p.id=j.printer_id LEFT JOIN print_job_files f ON f.print_job_id=j.id ORDER BY j.created_at DESC LIMIT 200`);res.json({success:true,data:rows});}catch(e){next(e);}});
router.get('/:id',async(req,res,next)=>{try{const {rows}=await query(`SELECT j.*,p.name printer_name,f.file_name,f.storage_path,f.mime_type FROM print_jobs j JOIN printers p ON p.id=j.printer_id LEFT JOIN print_job_files f ON f.print_job_id=j.id WHERE j.id=$1`,[req.params.id]);if(!rows[0])return res.status(404).json({success:false,message:'Print job not found.'});res.json({success:true,data:rows[0]});}catch(e){next(e);}});
router.patch('/:id/cancel',async(req,res,next)=>{try{const {rows}=await query(`UPDATE print_jobs SET status='cancelled',updated_at=now() WHERE id=$1 AND status='queued' RETURNING *`,[req.params.id]);if(!rows[0])return res.status(409).json({success:false,message:'Job cannot be cancelled now.'});res.json({success:true,data:rows[0]});}catch(e){next(e);}});
export default router;
